In [1]:
import pandas as pd
import numpy as np

df_team_probs = pd.read_csv('../resources/data/preprocessed/mens_team_probs.csv')

df_team_probs

team_id       team_name region  seed  play_in  round0_cdf  round1_cdf  \
0      1222         Houston      Y     1        0         1.0         1.0   
1      1104         Alabama      X     1        0         1.0         1.0   
2      1417            UCLA      Z     2        0         1.0         1.0   
3      1211         Gonzaga      Z     3        0         1.0         1.0   
4      1242          Kansas      Z     1        0         1.0         1.0   
..      ...             ...    ...   ...      ...         ...         ...   
59     1244        Kennesaw      Y    14        0         1.0         1.0   
60     1421   UNC Asheville      Z    15        0         1.0         1.0   
61     1224          Howard      Z    16        0         1.0         1.0   
62     1394  TAM C. Christi      X    16        1         1.0         1.0   
63     1192     F Dickinson      W    16        1         1.0         1.0   

    round2_cdf  round3_cdf  round4_cdf  ...  public_round4_cdf  \
0       0.9497      0.7593      0.5899  ...               0.67   
1       0.9758      0.7638      0.5380  ...               0.74   
2       0.9124      0.6860      0.3946  ...               0.46   
3       0.8880      0.6640      0.3754  ...               0.37   
4       0.9761      0.7453      0.4683  ...               0.60   
..         ...         ...         ...  ...                ...   
59      0.1231      0.0196      0.0019  ...               0.00   
60      0.0876      0.0146      0.0013  ...               0.01   
61      0.0239      0.0032      0.0002  ...               0.01   
62      0.0242      0.0011      0.0001  ...               0.00   
63      0.0224      0.0004      0.0000  ...               0.00   

    public_round5_cdf  public_round6_cdf  public_round7_cdf  round2_gain  \
0                0.45               0.27               0.15      -0.0003   
1                0.53               0.36               0.19       0.0158   
2                0.23               0.12               0.06      -0.0276   
3                0.18               0.09               0.04      -0.0320   
4                0.35               0.19               0.10       0.0261   
..                ...                ...                ...          ...   
59               0.00               0.00               0.00       0.0331   
60               0.00               0.00               0.00       0.0376   
61               0.00               0.00               0.00      -0.0161   
62               0.00               0.00               0.00      -0.0058   
63               0.00               0.00               0.00      -0.0076   

    round3_gain  round4_gain  round5_gain  round6_gain  round7_gain  
0       -0.0707      -0.0801      -0.0571      -0.0389      -0.0071  
1       -0.1062      -0.2020      -0.1646      -0.1246      -0.0545  
2       -0.1340      -0.0654       0.0025       0.0112       0.0156  
3       -0.0360       0.0054       0.0347       0.0285       0.0302  
4       -0.0647      -0.1317      -0.0995      -0.0553      -0.0307  
..          ...          ...          ...          ...          ...  
59      -0.0104       0.0019       0.0001       0.0000       0.0000  
60      -0.0054      -0.0087       0.0000       0.0000       0.0000  
61      -0.0068      -0.0098       0.0000       0.0000       0.0000  
62      -0.0089       0.0001       0.0000       0.0000       0.0000  
63      -0.0096       0.0000       0.0000       0.0000       0.0000  

[64 rows x 25 columns]

Until I update other file:

In [2]:
# df_team_probs.columns

In [3]:
# df_team_probs = df_team_probs[['team_id', 'team_name', 'region', 'seed', 'play_in', 'round0_cdf',
#        'round1_cdf', 'round2_cdf', 'round3_cdf', 'round4_cdf', 'round5_cdf',
#        'round6_cdf', 'round7_cdf']]

# df_team_probs

In [4]:
# df_public = pd.read_pickle('../resources/data/preprocessed/mens_public.pkl')

# df_public

In [5]:
# from fuzzywuzzy.fuzz import token_sort_ratio
# from fuzzywuzzy import process

# def find_string_match(team, seed, df_team_probs=df_team_probs):
#     team_names = df_team_probs.loc[df_team_probs['seed'] == seed, 'team_name'].copy()
    
#     return [team, *process.extract(team, team_names, scorer=token_sort_ratio, limit=1)[0][:2]]

# team_guess = pd.DataFrame(
#     [find_string_match(team, seed) 
#      for team, seed in np.array(df_public[['team', 'seed']])], columns = ['public_team', 'kaggle_team', 'score']
# ).sort_values(['score'], ignore_index=True)

# team_guess.head(20)

In [6]:
# team_guess.loc[team_guess['public_team'] == 'FAU', 'kaggle_team'] = 'FL Atlantic'

# team_guess.head(20)

In [7]:
# team_mapper = dict(zip(team_guess['public_team'], team_guess['kaggle_team']))

# df_public['team'] = df_public['team'].map(team_mapper)

# df_public

In [8]:
# df_team_probs = pd.merge(df_team_probs, df_public, how='left', 
#                          left_on=['seed', 'team_name'], right_on=['seed', 'team']).drop(columns=['team'])

# df_team_probs

In [9]:
df_team_probs.set_index('team_id', inplace=True)

df_team_probs

team_name region  seed  play_in  round0_cdf  round1_cdf  \
team_id                                                                 
1222            Houston      Y     1        0         1.0         1.0   
1104            Alabama      X     1        0         1.0         1.0   
1417               UCLA      Z     2        0         1.0         1.0   
1211            Gonzaga      Z     3        0         1.0         1.0   
1242             Kansas      Z     1        0         1.0         1.0   
...                 ...    ...   ...      ...         ...         ...   
1244           Kennesaw      Y    14        0         1.0         1.0   
1421      UNC Asheville      Z    15        0         1.0         1.0   
1224             Howard      Z    16        0         1.0         1.0   
1394     TAM C. Christi      X    16        1         1.0         1.0   
1192        F Dickinson      W    16        1         1.0         1.0   

         round2_cdf  round3_cdf  round4_cdf  round5_cdf  ...  \
team_id                                                  ...   
1222         0.9497      0.7593      0.5899      0.3929  ...   
1104         0.9758      0.7638      0.5380      0.3654  ...   
1417         0.9124      0.6860      0.3946      0.2325  ...   
1211         0.8880      0.6640      0.3754      0.2147  ...   
1242         0.9761      0.7453      0.4683      0.2505  ...   
...             ...         ...         ...         ...  ...   
1244         0.1231      0.0196      0.0019      0.0001  ...   
1421         0.0876      0.0146      0.0013      0.0000  ...   
1224         0.0239      0.0032      0.0002      0.0000  ...   
1394         0.0242      0.0011      0.0001      0.0000  ...   
1192         0.0224      0.0004      0.0000      0.0000  ...   

         public_round4_cdf  public_round5_cdf  public_round6_cdf  \
team_id                                                            
1222                  0.67               0.45               0.27   
1104                  0.74               0.53               0.36   
1417                  0.46               0.23               0.12   
1211                  0.37               0.18               0.09   
1242                  0.60               0.35               0.19   
...                    ...                ...                ...   
1244                  0.00               0.00               0.00   
1421                  0.01               0.00               0.00   
1224                  0.01               0.00               0.00   
1394                  0.00               0.00               0.00   
1192                  0.00               0.00               0.00   

         public_round7_cdf  round2_gain  round3_gain  round4_gain  \
team_id                                                             
1222                  0.15      -0.0003      -0.0707      -0.0801   
1104                  0.19       0.0158      -0.1062      -0.2020   
1417                  0.06      -0.0276      -0.1340      -0.0654   
1211                  0.04      -0.0320      -0.0360       0.0054   
1242                  0.10       0.0261      -0.0647      -0.1317   
...                    ...          ...          ...          ...   
1244                  0.00       0.0331      -0.0104       0.0019   
1421                  0.00       0.0376      -0.0054      -0.0087   
1224                  0.00      -0.0161      -0.0068      -0.0098   
1394                  0.00      -0.0058      -0.0089       0.0001   
1192                  0.00      -0.0076      -0.0096       0.0000   

         round5_gain  round6_gain  round7_gain  
team_id                                         
1222         -0.0571      -0.0389      -0.0071  
1104         -0.1646      -0.1246      -0.0545  
1417          0.0025       0.0112       0.0156  
1211          0.0347       0.0285       0.0302  
1242         -0.0995      -0.0553      -0.0307  
...              ...          ...          ...  
1244          0.0001       0.0000       0.0000  
1421   

In [10]:
# df_team_probs[['round' + str(i) + '_gain' for i in range(2, 8)]] = (
#     df_team_probs[['round' + str(i) + '_cdf' for i in range(2, 8)]].to_numpy() - 
#     df_team_probs[['public_round' + str(i) + '_cdf' for i in range(2, 8)]].to_numpy()
# )

# df_team_probs

In [11]:
# for round_number in range(2, 8):
#     df_team_probs[f'public_round{round_number}_cdf'] = (
#         df_team_probs[f'public_round{round_number}_cdf']*
#         (2**(7-round_number))/
#         df_team_probs[f'public_round{round_number}_cdf'].sum()
#     )

In [12]:
# df_team_probs[f'public_round6_cdf'].sum()

In [13]:
df_seeds = pd.read_csv('../resources/data/unprocessed/MNCAATourneySeeds.csv')

df_seeds = df_seeds.loc[df_seeds['Season'] == 2023, :].drop(columns=['Season']).reset_index(drop=True)

df_seeds['PlayIn'] = 0
df_seeds.loc[df_seeds['Seed'].str[-1].str.isalpha(), 'PlayIn'] = 1

df_seeds['Region'] = df_seeds['Seed'].str[0]

df_seeds['Seed'] = df_seeds['Seed'].str.extract('(\d+)').astype(int)

df_seeds

Seed  TeamID  PlayIn Region
0      1    1345       0      W
1      2    1266       0      W
2      3    1243       0      W
3      4    1397       0      W
4      5    1181       0      W
..   ...     ...     ...    ...
63    12    1433       0      Z
64    13    1233       0      Z
65    14    1213       0      Z
66    15    1421       0      Z
67    16    1224       0      Z

[68 rows x 4 columns]

In [14]:
def create_bracket_list(df_seeds=df_seeds):
    round0 = []
    region = ['W', 'X', 'Y', 'Z']
    for r in region:
        # print(r)
        for s in [1, 8, 5, 4, 6, 3, 7, 2]:
            a = df_seeds.loc[(df_seeds['Region'] == r) & (df_seeds['Seed'] == s), 'TeamID']
            if a.shape[0] == 1: round0.append([a.iloc[0]])
            else: round0.append([a.iloc[0], a.iloc[1]])
            
            b = df_seeds.loc[(df_seeds['Region'] == r) & (df_seeds['Seed'] == 17 - s), 'TeamID']
            if b.shape[0] == 1: round0.append([b.iloc[0]])
            else: round0.append([b.iloc[0], b.iloc[1]])
            
            # print()
    return round0
            
round0 = create_bracket_list()

# remove playins
round0[1] = [1192]
round0[17] = [1394]
round0[41] = [1338]
round0[-7] = [1113]

# reorder to match ESPN
round0 = round0[16:32] + round0[:16] + round0[32:64]

teams = [i[0] for i in round0]

teams

[1104,
 1394,
 1268,
 1452,
 1361,
 1158,
 1438,
 1202,
 1166,
 1301,
 1124,
 1364,
 1281,
 1429,
 1112,
 1343,
 1345,
 1192,
 1272,
 1194,
 1181,
 1331,
 1397,
 1418,
 1246,
 1344,
 1243,
 1286,
 1277,
 1425,
 1266,
 1436,
 1222,
 1297,
 1234,
 1120,
 1274,
 1179,
 1231,
 1245,
 1235,
 1338,
 1462,
 1244,
 1401,
 1336,
 1400,
 1159,
 1242,
 1224,
 1116,
 1228,
 1388,
 1433,
 1163,
 1233,
 1395,
 1113,
 1211,
 1213,
 1321,
 1129,
 1417,
 1421]

Create splits in advance to save processing time

In [15]:
df_team_probs = df_team_probs.loc[teams, :]

df_team_probs

team_name region  seed  play_in  round0_cdf  round1_cdf  \
team_id                                                                 
1104            Alabama      X     1        0         1.0         1.0   
1394     TAM C. Christi      X    16        1         1.0         1.0   
1268           Maryland      X     8        0         1.0         1.0   
1452      West Virginia      X     9        0         1.0         1.0   
1361       San Diego St      X     5        0         1.0         1.0   
...                 ...    ...   ...      ...         ...         ...   
1213       Grand Canyon      Z    14        0         1.0         1.0   
1321       Northwestern      Z     7        0         1.0         1.0   
1129           Boise St      Z    10        0         1.0         1.0   
1417               UCLA      Z     2        0         1.0         1.0   
1421      UNC Asheville      Z    15        0         1.0         1.0   

         round2_cdf  round3_cdf  round4_cdf  round5_cdf  ...  \
team_id                                                  ...   
1104         0.9758      0.7638      0.5380      0.3654  ...   
1394         0.0242      0.0011      0.0001      0.0000  ...   
1268         0.4773      0.1114      0.0534      0.0221  ...   
1452         0.5227      0.1237      0.0678      0.0286  ...   
1361         0.7047      0.3903      0.1603      0.0799  ...   
...             ...         ...         ...         ...  ...   
1213         0.1120      0.0219      0.0031      0.0001  ...   
1321         0.5148      0.1416      0.0396      0.0106  ...   
1129         0.4852      0.1578      0.0655      0.0222  ...   
1417         0.9124      0.6860      0.3946      0.2325  ...   
1421         0.0876      0.0146      0.0013      0.0000  ...   

         public_round4_cdf  public_round5_cdf  public_round6_cdf  \
team_id                                                            
1104                  0.74               0.53               0.36   
1394                  0.00               0.00               0.00   
1268                  0.02               0.01               0.00   
1452                  0.02               0.01               0.00   
1361                  0.05               0.02               0.00   
...                    ...                ...                ...   
1213                  0.00               0.00               0.00   
1321                  0.03               0.01               0.00   
1129                  0.01               0.00               0.00   
1417                  0.46               0.23               0.12   
1421                  0.01               0.00               0.00   

         public_round7_cdf  round2_gain  round3_gain  round4_gain  \
team_id                                                             
1104                  0.19       0.0158      -0.1062      -0.2020   
1394                  0.00      -0.0058      -0.0089       0.0001   
1268                  0.00      -0.0127       0.0614       0.0334   
1452                  0.00       0.0127       0.0737       0.0478   
1361                  0.00       0.0247       0.0803       0.1103   
...                    ...          ...          ...          ...   
1213                  0.00       0.0420       0.0019       0.0031   
1321                  0.00      -0.0552       0.0516       0.0096   
1129                  0.00       0.0652       0.1078       0.0555   
1417                  0.06      -0.0276      -0.1340      -0.0654   
1421                  0.00       0.0376      -0.0054      -0.0087   

         round5_gain  round6_gain  round7_gain  
team_id                                         
1104         -0.1646      -0.1246      -0.0545  
1394          0.0000       0.0000       0.0000  
1268          0.0121       0.0079       0.0022  
1452          0.0186       0.0114       0.0047  
1361          0.0599       0.0371       0.0155  
...              ...          ...          ...  
1213          0.0001       0.0000       0.0000  
1321   

In [16]:
champion = [teams]
champion_probs = [df_team_probs.iloc[:, df_team_probs.columns.get_loc('round7_cdf')].tolist()]
champion_public_probs = [df_team_probs.iloc[:, df_team_probs.columns.get_loc('public_round7_cdf')].tolist()]

finals = [teams[:32], teams[32:]]
finals_probs = [df_team_probs.iloc[:32, df_team_probs.columns.get_loc('round6_cdf')].tolist(), 
                df_team_probs.iloc[32:, df_team_probs.columns.get_loc('round6_cdf')].tolist()]
finals_public_probs = [df_team_probs.iloc[:32, df_team_probs.columns.get_loc('public_round6_cdf')].tolist(), 
                       df_team_probs.iloc[32:, df_team_probs.columns.get_loc('public_round6_cdf')].tolist()]

final_four = [teams[i:(i+16)] for i in range(0, 64, 16)]
final_four_probs = [df_team_probs.iloc[i:(i+16), 
                                       df_team_probs.columns.get_loc('round5_cdf')].tolist() 
                    for i in range(0, 64, 16)]
final_four_public_probs = [df_team_probs.iloc[i:(i+16), 
                                              df_team_probs.columns.get_loc('public_round5_cdf')].tolist() 
                           for i in range(0, 64, 16)]

elite_eight = [teams[i:(i+8)] for i in range(0, 64, 8)]
elite_eight_probs = [df_team_probs.iloc[i:(i+8), 
                                        df_team_probs.columns.get_loc('round4_cdf')].tolist() 
                     for i in range(0, 64, 8)]
elite_eight_public_probs = [df_team_probs.iloc[i:(i+8), 
                                               df_team_probs.columns.get_loc('public_round4_cdf')].tolist() 
                            for i in range(0, 64, 8)]

sweet_sixteen = [teams[i:(i+4)] for i in range(0, 64, 4)]
sweet_sixteen_probs = [df_team_probs.iloc[i:(i+4), 
                                         df_team_probs.columns.get_loc('round3_cdf')].tolist() 
                       for i in range(0, 64, 4)]
sweet_sixteen_public_probs = [df_team_probs.iloc[i:(i+4), 
                                                 df_team_probs.columns.get_loc('public_round3_cdf')].tolist() 
                              for i in range(0, 64, 4)]

round_of_32 = [teams[i:(i+2)] for i in range(0, 64, 2)]
round_of_32_probs = [df_team_probs.iloc[i:(i+2), 
                                        df_team_probs.columns.get_loc('round2_cdf')].tolist() 
                     for i in range(0, 64, 2)]
round_of_32_public_probs = [df_team_probs.iloc[i:(i+2), 
                                               df_team_probs.columns.get_loc('public_round2_cdf')].tolist() 
                            for i in range(0, 64, 2)]

sweet_sixteen_probs

[[0.7638, 0.0011, 0.1114, 0.1237],
 [0.3903, 0.1315, 0.4559, 0.0223],
 [0.3185, 0.0943, 0.5743, 0.0129],
 [0.1411, 0.2588, 0.5767, 0.0234],
 [0.5991, 0.0004, 0.2433, 0.1572],
 [0.4169, 0.0695, 0.4858, 0.0278],
 [0.3456, 0.1639, 0.4684, 0.0221],
 [0.2317, 0.1471, 0.6043, 0.0169],
 [0.7593, 0.0058, 0.0871, 0.1478],
 [0.3053, 0.1573, 0.4576, 0.0798],
 [0.3423, 0.0797, 0.5584, 0.0196],
 [0.2756, 0.13, 0.5675, 0.0269],
 [0.7453, 0.0032, 0.1743, 0.0772],
 [0.2912, 0.1409, 0.5132, 0.0547],
 [0.2652, 0.0489, 0.664, 0.0219],
 [0.1416, 0.1578, 0.686, 0.0146]]

In [17]:
round_teams = {
    6: champion,
    5: finals, 
    4: final_four, 
    3: elite_eight, 
    2: sweet_sixteen, 
    1: round_of_32
}

round_model_probs = {
    6: champion_probs,
    5: finals_probs, 
    4: final_four_probs, 
    3: elite_eight_probs, 
    2: sweet_sixteen_probs, 
    1: round_of_32_probs
}


round_public_probs = {
    6: champion_public_probs,
    5: finals_public_probs, 
    4: final_four_public_probs, 
    3: elite_eight_public_probs, 
    2: sweet_sixteen_public_probs, 
    1: round_of_32_public_probs
}

# round_teams
'Done'

'Done'

In [18]:
round_public_probs[6] = np.array(round_public_probs[6])
round_public_probs[6] = round_public_probs[6]/round_public_probs[6].sum()

round_public_probs[5] = np.array(round_public_probs[5])
round_public_probs[5][0, :] = round_public_probs[5][0, :]/round_public_probs[5][0, :].sum()
round_public_probs[5][1, :] = round_public_probs[5][1, :]/round_public_probs[5][1, :].sum()


round_number = 4
round_public_probs[round_number] = np.array(round_public_probs[round_number])
for i in range(4):
    round_public_probs[round_number][i, :] = (
        round_public_probs[round_number][i, :]/round_public_probs[round_number][i, :].sum()
    )
    
    
round_number = 3
round_public_probs[round_number] = np.array(round_public_probs[round_number])
for i in range(8):
    round_public_probs[round_number][i, :] = (
        round_public_probs[round_number][i, :]/round_public_probs[round_number][i, :].sum()
    )
    
round_number = 2
round_public_probs[round_number] = np.array(round_public_probs[round_number])
for i in range(16):
    round_public_probs[round_number][i, :] = (
        round_public_probs[round_number][i, :]/round_public_probs[round_number][i, :].sum()
    )
    
round_number = 1
round_public_probs[round_number] = np.array(round_public_probs[round_number])
for i in range(32):
    round_public_probs[round_number][i, :] = (
        round_public_probs[round_number][i, :]/round_public_probs[round_number][i, :].sum()
    )
    
round_public_probs[1].sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
round_model_probs[6] = np.array(round_model_probs[6])
round_model_probs[6] = round_model_probs[6]/round_model_probs[6].sum()

round_model_probs[5] = np.array(round_model_probs[5])
round_model_probs[5][0, :] = round_model_probs[5][0, :]/round_model_probs[5][0, :].sum()
round_model_probs[5][1, :] = round_model_probs[5][1, :]/round_model_probs[5][1, :].sum()


round_number = 4
round_model_probs[round_number] = np.array(round_model_probs[round_number])
for i in range(4):
    round_model_probs[round_number][i, :] = (
        round_model_probs[round_number][i, :]/round_model_probs[round_number][i, :].sum()
    )
    
    
round_number = 3
round_model_probs[round_number] = np.array(round_model_probs[round_number])
for i in range(8):
    round_model_probs[round_number][i, :] = (
        round_model_probs[round_number][i, :]/round_model_probs[round_number][i, :].sum()
    )
    
round_number = 2
round_model_probs[round_number] = np.array(round_model_probs[round_number])
for i in range(16):
    round_model_probs[round_number][i, :] = (
        round_model_probs[round_number][i, :]/round_model_probs[round_number][i, :].sum()
    )
    
round_number = 1
round_model_probs[round_number] = np.array(round_model_probs[round_number])
for i in range(32):
    round_model_probs[round_number][i, :] = (
        round_model_probs[round_number][i, :]/round_model_probs[round_number][i, :].sum()
    )
    
round_model_probs[1].sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
def get_round_survivors(teams, probs, used_teams):        
    new_teams = set()
    for index, pool in enumerate(teams):
        intersect = used_teams.intersection(pool)
        if len(intersect) == 0:
            pool_probs = np.array(probs[index, :])
            new_teams.add(np.random.choice(pool, p=pool_probs))
    
    return new_teams

get_round_survivors(round_teams[6], round_model_probs[6], set())

{1400}

In [21]:
def create_bracket(round_probs, round_teams=round_teams): 
    # print('CHAMPION')
    used_teams = get_round_survivors(round_teams[6], round_probs[6], set())
    bracket = dict(zip(used_teams, np.repeat(6, 1)))
    # print(survivors)
    # print()
    
    # print('CHAMPIONSHIP')    
    new_teams = get_round_survivors(round_teams[5], round_probs[5], used_teams)
    bracket.update(dict(zip(new_teams, np.repeat(5, 1))))
    used_teams.update(new_teams)
    # print(survivors)
    # print()
    
    # print('FINAL FOUR')    
    new_teams = get_round_survivors(round_teams[4], round_probs[4], used_teams)
    bracket.update(dict(zip(new_teams, np.repeat(4, 2))))
    used_teams.update(new_teams)
    # print(survivors)
    # print()
    
    # print('ELITE EIGHT')    
    new_teams = get_round_survivors(round_teams[3], round_probs[3], used_teams)
    bracket.update(dict(zip(new_teams, np.repeat(3, 4))))
    used_teams.update(new_teams)
    # print(survivors)
    # print()
    
    # print('SWEET SIXTEEN')    
    new_teams = get_round_survivors(round_teams[2], round_probs[2], used_teams)
    bracket.update(dict(zip(new_teams, np.repeat(2, 8))))
    used_teams.update(new_teams)
    # print(survivors)
    # print()
    
    # print('ROUND OF 32')    
    new_teams = get_round_survivors(round_teams[1], round_probs[1], used_teams)
    bracket.update(dict(zip(new_teams, np.repeat(1, 16))))
    used_teams.update(new_teams)
    # print(survivors)
    # print()
    
    return bracket

create_bracket(round_model_probs)

{1400: 6,
 1124: 5,
 1345: 4,
 1211: 4,
 1242: 3,
 1234: 3,
 1452: 3,
 1246: 3,
 1129: 2,
 1163: 2,
 1425: 2,
 1235: 2,
 1112: 2,
 1274: 2,
 1181: 2,
 1438: 2,
 1281: 1,
 1222: 1,
 1417: 1,
 1194: 1,
 1388: 1,
 1166: 1,
 1104: 1,
 1361: 1,
 1266: 1,
 1397: 1,
 1462: 1,
 1336: 1,
 1113: 1,
 1243: 1,
 1116: 1,
 1245: 1}

In [22]:
# %%timeit

# create_bracket(round_model_probs)

In [23]:
public_bracket = create_bracket(round_public_probs)

public_bracket

{1104: 6,
 1462: 5,
 1417: 4,
 1181: 4,
 1112: 3,
 1242: 3,
 1266: 3,
 1222: 3,
 1345: 2,
 1179: 2,
 1388: 2,
 1166: 2,
 1211: 2,
 1401: 2,
 1243: 2,
 1438: 2,
 1281: 1,
 1159: 1,
 1321: 1,
 1163: 1,
 1228: 1,
 1231: 1,
 1361: 1,
 1425: 1,
 1234: 1,
 1268: 1,
 1364: 1,
 1397: 1,
 1272: 1,
 1113: 1,
 1338: 1,
 1246: 1}

In [24]:
actual_results = create_bracket(round_model_probs)

actual_results

{1222: 6,
 1397: 5,
 1388: 4,
 1124: 4,
 1104: 3,
 1417: 3,
 1344: 3,
 1400: 3,
 1345: 2,
 1158: 2,
 1231: 2,
 1266: 2,
 1235: 2,
 1429: 2,
 1242: 2,
 1211: 2,
 1272: 1,
 1120: 1,
 1401: 1,
 1129: 1,
 1163: 1,
 1179: 1,
 1228: 1,
 1395: 1,
 1268: 1,
 1301: 1,
 1112: 1,
 1277: 1,
 1243: 1,
 1244: 1,
 1181: 1,
 1438: 1}

In [25]:
def score_bracket(actual, predicted):
    score = 0
    for team, predicted_finish in predicted.items():
        if actual_placement := actual.get(team):
            if actual_placement < predicted_finish:
                predicted_finish = actual_placement
                
            if predicted_finish == 1:
                score += 10
            elif predicted_finish == 2:
                score += 30
            elif predicted_finish == 3:
                score += 70
            elif predicted_finish == 4:
                score += 150
            elif predicted_finish == 5:
                score += 310
            elif predicted_finish == 6:
                score += 630
                
    return score

score_bracket(public_bracket, actual_results)

480

In [26]:
# %%timeit

# score_bracket(public_bracket, actual_results)

In [27]:
%%time

pool = [create_bracket(round_public_probs) for _ in range(20_000)]

'Done'

CPU times: total: 22 s
Wall time: 22 s


'Done'

In [28]:
%%time

potential_brackets = (
    [create_bracket(round_model_probs) for _ in range(20_000)] +
    pool
)

'Done'

CPU times: total: 23.8 s
Wall time: 23.8 s


'Done'

In [29]:
%%time

actuals = [create_bracket(round_model_probs) for _ in range(20_000)]

'Done'

CPU times: total: 23.5 s
Wall time: 23.5 s


'Done'

In [30]:
%%time

pool_scores = np.array([[score_bracket(v, w) for v in pool] for w in actuals])

pool_scores

CPU times: total: 1h 19min 15s
Wall time: 1h 19min 17s


array([[ 590,  620,  530, ...,  650,  970,  690],
       [1050,  540,  370, ...,  690,  650,  570],
       [ 730,  660,  750, ...,  910, 1250,  890],
       ...,
       [ 710,  640,  610, ...,  730,  730,  710],
       [ 790,  440,  510, ...,  590,  490,  530],
       [ 640,  750,  600, ...,  520,  920,  720]])

In [31]:
pool_scores.mean()

714.20169055

In [32]:
%%time

potential_brackets_scores = np.array(
    [[score_bracket(v, w) 
      for v in potential_brackets[:len(potential_brackets)//2]] 
     for w in actuals]
)

potential_brackets_scores = np.hstack((potential_brackets_scores, pool_scores))

potential_brackets_scores

CPU times: total: 1h 17min 18s
Wall time: 1h 17min 21s


array([[ 500,  590,  540, ...,  650,  970,  690],
       [ 420,  630,  500, ...,  690,  650,  570],
       [ 460,  770,  420, ...,  910, 1250,  890],
       ...,
       [ 420,  630,  580, ...,  730,  730,  710],
       [ 700, 1250,  400, ...,  590,  490,  530],
       [ 790, 1220,  710, ...,  520,  920,  720]])

In [33]:
potential_brackets_scores.shape

(20000, 40000)

In [34]:
potential_brackets_scores.mean()

680.9581837

In [35]:
pool_size = 103

winning_scores = np.percentile(pool_scores, 100 - (100/pool_size), axis=1)
second_scores = np.percentile(pool_scores, 100 - (200/pool_size), axis=1)
third_scores = np.percentile(pool_scores, 100 - (300/pool_size), axis=1)

winning_scores[:10]

array([1400., 1260., 1470., 1270., 1440., 1240., 1010., 1180., 1290.,
       1340.])

In [36]:
second_scores[:10]

array([1310.        , 1190.        , 1430.        , 1176.69902913,
       1370.        , 1210.        ,  960.        , 1100.        ,
       1260.        , 1280.        ])

In [37]:
third_scores[:10]

array([1230.        , 1140.        , 1390.        , 1120.        ,
       1330.        , 1190.        ,  925.04854369, 1060.        ,
       1230.        , 1210.        ])

In [38]:
# remember to subtract subsequent placement

buyin = 20

potential_brackets_payout = (
    np.array(
        [potential_brackets_scores[i, :] >= winning_scores[i] 
         for i in range(winning_scores.shape[0])]
    )*(0.7 - 0.2) +
    np.array(
        [potential_brackets_scores[i, :] >= second_scores[i] 
         for i in range(second_scores.shape[0])]
    )*(0.2 - 0.1) +
    np.array(
        [potential_brackets_scores[i, :] >= third_scores[i] 
         for i in range(third_scores.shape[0])]
    )*(0.1)
)*pool_size*buyin

potential_brackets_payout

array([[  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0., 412.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

In [39]:
potential_brackets_expected_payout = potential_brackets_payout.mean(axis=0)

potential_brackets_expected_payout.max()

70.4829

In [40]:
potential_brackets_expected_payout.min()

0.3605

In [41]:
best_bracket = potential_brackets_expected_payout.argmax()

best_bracket

36084

In [42]:
(potential_brackets_payout[:, best_bracket] > 0).mean()

0.08095

In [43]:
potential_brackets[best_bracket]

{1211: 6,
 1104: 5,
 1266: 4,
 1222: 4,
 1112: 3,
 1345: 3,
 1242: 3,
 1462: 3,
 1124: 2,
 1417: 2,
 1163: 2,
 1231: 2,
 1361: 2,
 1400: 2,
 1243: 2,
 1181: 2,
 1120: 1,
 1281: 1,
 1336: 1,
 1113: 1,
 1129: 1,
 1388: 1,
 1166: 1,
 1235: 1,
 1268: 1,
 1397: 1,
 1272: 1,
 1277: 1,
 1274: 1,
 1116: 1,
 1246: 1,
 1438: 1}

In [44]:
def print_bracket(bracket_dict, df_team_probs=df_team_probs):
    df_team_probs = df_team_probs.copy()
    teams = list(bracket_dict.keys())
    print(f'{"-"*22} CHAMPION {"-"*22}')
    print(df_team_probs.loc[[team for team in df_team_probs.index if team in teams[:1]], 
                            ['team_name', 'region', 'seed', 
                             f'round7_cdf', f'round7_gain']])
    print('\n')
    
    print(f'{"-"*22} FINALS {"-"*22}')
    print(df_team_probs.loc[[team for team in df_team_probs.index if team in teams[:2]], 
                            ['team_name', 'region', 'seed', 
                             f'round6_cdf', f'round6_gain']])
    print('\n')
    
    print(f'{"-"*22} FINAL FOUR {"-"*22}')
    print(df_team_probs.loc[[team for team in df_team_probs.index if team in teams[:4]], 
                            ['team_name', 'region', 'seed', 
                             f'round5_cdf', f'round5_gain']])
    print('\n')
    
    print(f'{"-"*22} ELITE EIGHT {"-"*22}')
    print(df_team_probs.loc[[team for team in df_team_probs.index if team in teams[:8]], 
                            ['team_name', 'region', 'seed', 
                             f'round4_cdf', f'round4_gain']])
    print('\n')
    
    print(f'{"-"*22} SWEET SIXTEEN {"-"*22}')
    print(df_team_probs.loc[[team for team in df_team_probs.index if team in teams[:16]], 
                            ['team_name', 'region', 'seed', 
                             f'round3_cdf', f'round3_gain']])
    print('\n')
    
    print(f'{"-"*22} ROUND OF 32 {"-"*22}')
    print(df_team_probs.loc[[team for team in df_team_probs.index if team in teams[:32]], 
                            ['team_name', 'region', 'seed', 
                             f'round2_cdf', f'round2_gain']])

print_bracket(potential_brackets[best_bracket])

---------------------- CHAMPION ----------------------
        team_name region  seed  round7_cdf  round7_gain
team_id                                                
1211      Gonzaga      Z     3      0.0702       0.0302


---------------------- FINALS ----------------------
        team_name region  seed  round6_cdf  round6_gain
team_id                                                
1104      Alabama      X     1      0.2354      -0.1246
1211      Gonzaga      Z     3      0.1185       0.0285


---------------------- FINAL FOUR ----------------------
         team_name region  seed  round5_cdf  round5_gain
team_id                                                 
1104       Alabama      X     1      0.3654      -0.1646
1266     Marquette      W     2      0.2246       0.0346
1222       Houston      Y     1      0.3929      -0.0571
1211       Gonzaga      Z     3      0.2147       0.0347


---------------------- ELITE EIGHT ----------------------
         team_name region  seed  roun

In [45]:
print_bracket(potential_brackets[np.argmax(potential_brackets_scores.mean(axis=0))])

---------------------- CHAMPION ----------------------
        team_name region  seed  round7_cdf  round7_gain
team_id                                                
1104      Alabama      X     1      0.1355      -0.0545


---------------------- FINALS ----------------------
        team_name region  seed  round6_cdf  round6_gain
team_id                                                
1104      Alabama      X     1      0.2354      -0.1246
1222      Houston      Y     1      0.2311      -0.0389


---------------------- FINAL FOUR ----------------------
        team_name region  seed  round5_cdf  round5_gain
team_id                                                
1104      Alabama      X     1      0.3654      -0.1646
1345       Purdue      W     1      0.2278      -0.0922
1222      Houston      Y     1      0.3929      -0.0571
1417         UCLA      Z     2      0.2325       0.0025


---------------------- ELITE EIGHT ----------------------
         team_name region  seed  round4_cdf

In [46]:
(potential_brackets_payout[:, np.argmax(potential_brackets_scores.mean(axis=0))] > 0).mean()

0.0504

In [47]:
potential_brackets_expected_payout[np.argmax(potential_brackets_scores.mean(axis=0))]

31.6828

In [48]:
# def best_two_brackets(potential_brackets_payout=potential_brackets_payout):
#     potential_brackets_payout = potential_brackets_payout.copy()
    
#     best_bracket1_index = None
#     best_bracket2_index = None
#     best_expected_payout = 0
#     for index1, bracket1 in enumerate(potential_brackets_payout.T[:, :]):
#         index2 = np.argmax(potential_brackets_payout[bracket1 == 0, :].mean(axis=0))
#         expected_payout = bracket1.mean() + potential_brackets_payout[:, index2].mean()
            
#         if expected_payout > best_expected_payout:
#             best_bracket1_index = index1
#             best_bracket2_index = index2
#             best_expected_payout = expected_payout
        
#     return (best_bracket1_index, best_bracket2_index, best_expected_payout)

# # best_bracket1, best_bracket2, expected_payout = best_two_brackets()

# # best_bracket1, best_bracket2, expected_payout

# 'Done'

In [49]:
# %%time

# best_bracket1, best_bracket2, expected_payout = best_two_brackets()

# best_bracket1, best_bracket2, expected_payout

Only use top few brackets to make next part go faster

In [50]:
top_1000 = np.argpartition(potential_brackets_expected_payout, -1000)[-1000:]

top_1000.shape

(1000,)

In [51]:
potential_brackets_payout_top_1000 = potential_brackets_payout[:, top_1000]

potential_brackets_payout_top_1000.shape

(20000, 1000)

In [52]:
potential_brackets_top_1000 = [potential_brackets[i] for i in top_1000]

potential_brackets_top_1000[0]

{1211: 6,
 1104: 5,
 1345: 4,
 1222: 4,
 1112: 3,
 1242: 3,
 1266: 3,
 1336: 3,
 1417: 2,
 1166: 2,
 1231: 2,
 1397: 2,
 1462: 2,
 1433: 2,
 1243: 2,
 1438: 2,
 1344: 1,
 1124: 1,
 1400: 1,
 1158: 1,
 1321: 1,
 1163: 1,
 1452: 1,
 1338: 1,
 1228: 1,
 1234: 1,
 1331: 1,
 1395: 1,
 1429: 1,
 1272: 1,
 1274: 1,
 1277: 1}

In [53]:
def bracket_combo(index1, bracket1, potential_brackets_payout_top_1000=potential_brackets_payout_top_1000):
    index2 = np.argmax(potential_brackets_payout_top_1000[bracket1 == 0, :].mean(axis=0))
    expected_payout = bracket1.mean() + potential_brackets_payout_top_1000[:, index2].mean()
    
    return (index1, index2, expected_payout)

bracket_combo(84, potential_brackets_payout_top_1000[:, 84])

(84, 391, 112.4657)

In [54]:
%%time

bracket_combos = np.array(
    [bracket_combo(index1, bracket1) 
     for index1, bracket1 in enumerate(potential_brackets_payout_top_1000.T)]
)

bracket_combos

CPU times: total: 1min 19s
Wall time: 1min 19s


array([[  0.    , 575.    , 105.7501],
       [  1.    , 391.    , 111.9198],
       [  2.    , 575.    , 105.781 ],
       ...,
       [997.    , 575.    , 110.4366],
       [998.    , 391.    , 112.9704],
       [999.    , 575.    , 116.2664]])

In [55]:
bracket_combos[:, 2].max()

134.8064

In [56]:
best_bracket1, best_bracket2, expected_payout = bracket_combos[bracket_combos[:, 2].argmax(), :]

best_bracket1 = int(best_bracket1)
best_bracket2 = int(best_bracket2)

best_bracket1, best_bracket2, expected_payout

(575, 391, 134.8064)

In [57]:
best_bracket1

575

In [58]:
print_bracket(potential_brackets_top_1000[best_bracket1])

---------------------- CHAMPION ----------------------
         team_name region  seed  round7_cdf  round7_gain
team_id                                                 
1266     Marquette      W     2      0.0556       0.0256


---------------------- FINALS ----------------------
         team_name region  seed  round6_cdf  round6_gain
team_id                                                 
1266     Marquette      W     2      0.1122       0.0422
1222       Houston      Y     1      0.2311      -0.0389


---------------------- FINAL FOUR ----------------------
         team_name region  seed  round5_cdf  round5_gain
team_id                                                 
1104       Alabama      X     1      0.3654      -0.1646
1266     Marquette      W     2      0.2246       0.0346
1222       Houston      Y     1      0.3929      -0.0571
1242        Kansas      Z     1      0.2505      -0.0995


---------------------- ELITE EIGHT ----------------------
         team_name region  see

In [59]:
print_bracket(potential_brackets_top_1000[best_bracket2])

---------------------- CHAMPION ----------------------
        team_name region  seed  round7_cdf  round7_gain
team_id                                                
1211      Gonzaga      Z     3      0.0702       0.0302


---------------------- FINALS ----------------------
        team_name region  seed  round6_cdf  round6_gain
team_id                                                
1104      Alabama      X     1      0.2354      -0.1246
1211      Gonzaga      Z     3      0.1185       0.0285


---------------------- FINAL FOUR ----------------------
         team_name region  seed  round5_cdf  round5_gain
team_id                                                 
1104       Alabama      X     1      0.3654      -0.1646
1266     Marquette      W     2      0.2246       0.0346
1222       Houston      Y     1      0.3929      -0.0571
1211       Gonzaga      Z     3      0.2147       0.0347


---------------------- ELITE EIGHT ----------------------
         team_name region  seed  roun

SAVE

In [60]:
import pickle

with open('../resources/simulations/pool.pkl', 'wb') as handle:
    pickle.dump(pool, handle, protocol=pickle.HIGHEST_PROTOCOL)
    
with open('../resources/simulations/potential_brackets.pkl', 'wb') as handle:
    pickle.dump(potential_brackets, handle, protocol=pickle.HIGHEST_PROTOCOL)
    
with open('../resources/simulations/actuals.pkl', 'wb') as handle:
    pickle.dump(actuals, handle, protocol=pickle.HIGHEST_PROTOCOL)
    
with open('../resources/simulations/pool_scores.pkl', 'wb') as handle:
    pickle.dump(pool_scores, handle, protocol=pickle.HIGHEST_PROTOCOL)
    
with open('../resources/simulations/potential_brackets_scores.pkl', 'wb') as handle:
    pickle.dump(potential_brackets_scores, handle, protocol=pickle.HIGHEST_PROTOCOL)
    
'Done'

'Done'

In [63]:
np.argpartition(potential_brackets_expected_payout, -2)[-2:]

array([35317, 36084], dtype=int64)

In [65]:
print_bracket(potential_brackets[35317])

---------------------- CHAMPION ----------------------
        team_name region  seed  round7_cdf  round7_gain
team_id                                                
1211      Gonzaga      Z     3      0.0702       0.0302


---------------------- FINALS ----------------------
        team_name region  seed  round6_cdf  round6_gain
team_id                                                
1104      Alabama      X     1      0.2354      -0.1246
1211      Gonzaga      Z     3      0.1185       0.0285


---------------------- FINAL FOUR ----------------------
         team_name region  seed  round5_cdf  round5_gain
team_id                                                 
1104       Alabama      X     1      0.3654      -0.1646
1266     Marquette      W     2      0.2246       0.0346
1222       Houston      Y     1      0.3929      -0.0571
1211       Gonzaga      Z     3      0.2147       0.0347


---------------------- ELITE EIGHT ----------------------
         team_name region  seed  roun